### ISSUE TITLE
The icon for chrome is broken

### ISSUE THREAD

**Issue by Dohvakin** [zayronxio/Os-Catalina-icons#10]
![chrome icon issue](https://user-images.githubusercontent.com/26587446/82277520-b1364980-99a5-11ea-8746-1dc773f8d134.png)

**Comment by zayronxio** [comment]
In the last commits, add a new chrome icon, please try again.
let me know if the problem still persists.

**Comment by Dohvakin** [comment]
It's still broken on latest commit
![Screenshot_20200525_130509](https://user-images.githubusercontent.com/26587446/82789835-9d4c8500-9e88-11ea-84ec-7691f3d93916.png)

**Comment by zayronxio** [comment]
change the icon again, probably now

**Comment by Dohvakin** [comment]
It's fixed now.
