### ISSUE TITLE
Missing "night-light-disabled-symbolic" icon

### ISSUE THREAD

**Issue by Anarky** [zayronxio/Os-Catalina-icons#11]
Hello, elementary OS has a "night light" option, like redshift.
[With its indicator on their "wingpanel"](https://github.com/elementary/wingpanel-indicator-nightlight) it is possible to snooze the effect.
When it is snoozed, the indicator uses the "night-light-disabled-symbolic" icon; because it doesn't exist it becomes completely transparent.

Can you create it? Thanks!

PS: you can use the live USB to test it.

**Comment by zayronxio** [comment]
added
